snd-soc-simple-card-objs	:= simple-card.o
snd-soc-hw-params-rules-objs	:= hw-params-rules.o

obj-$(CONFIG_SND_SIMPLE_CARD)	+= snd-soc-simple-card.o
obj-$(CONFIG_SND_HW_PARAMS_RULES)	+= snd-soc-hw-params-rules.o
